//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColpatriaSAI.UI.MVC.ConsultasComisionesSVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultasComisionesSVC.IBitacoraCalculo")]
    public interface IBitacoraCalculo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/ListadoUsuariosCalculoComison", ReplyAction="http://tempuri.org/IBitacoraCalculo/ListadoUsuariosCalculoComisonResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoUsuariosCalculoComison();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/ListadoUsuariosCalculoComisonPorFechas", ReplyAction="http://tempuri.org/IBitacoraCalculo/ListadoUsuariosCalculoComisonPorFechasRespons" +
            "e")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoUsuariosCalculoComisonPorFechas(string fechIni, string fechFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/ListadoFacturasCalculoComison", ReplyAction="http://tempuri.org/IBitacoraCalculo/ListadoFacturasCalculoComisonResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoFacturasCalculoComison();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/ListadoRecaudosCalculoComison", ReplyAction="http://tempuri.org/IBitacoraCalculo/ListadoRecaudosCalculoComisonResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoRecaudosCalculoComison();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/DetalleUsuariosCalculoComison", ReplyAction="http://tempuri.org/IBitacoraCalculo/DetalleUsuariosCalculoComisonResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.DetalleUsuarios[] DetalleUsuariosCalculoComison(string codExtraccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/ExcelDetalleUsuario", ReplyAction="http://tempuri.org/IBitacoraCalculo/ExcelDetalleUsuarioResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.LogExtraccionBH[] ExcelDetalleUsuario(string codExtraccion, string tipoLog, string idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/DetalleFactura", ReplyAction="http://tempuri.org/IBitacoraCalculo/DetalleFacturaResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.DetalleFacturas[] DetalleFactura(string codExtraccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/ExcelDetalleFactura", ReplyAction="http://tempuri.org/IBitacoraCalculo/ExcelDetalleFacturaResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.LogExtFacturacion[] ExcelDetalleFactura(string codExtraccion, string tipoLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/DetalleRecaudo", ReplyAction="http://tempuri.org/IBitacoraCalculo/DetalleRecaudoResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.DetalleFacturas[] DetalleRecaudo(string codExtraccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoraCalculo/ExcelDetalleRecaudo", ReplyAction="http://tempuri.org/IBitacoraCalculo/ExcelDetalleRecaudoResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Consultas.LogExtracionRecaudo[] ExcelDetalleRecaudo(string codExtraccion, string tipoLog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBitacoraCalculoChannel : ColpatriaSAI.UI.MVC.ConsultasComisionesSVC.IBitacoraCalculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BitacoraCalculoClient : System.ServiceModel.ClientBase<ColpatriaSAI.UI.MVC.ConsultasComisionesSVC.IBitacoraCalculo>, ColpatriaSAI.UI.MVC.ConsultasComisionesSVC.IBitacoraCalculo {
        
        public BitacoraCalculoClient() {
        }
        
        public BitacoraCalculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BitacoraCalculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacoraCalculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacoraCalculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoUsuariosCalculoComison() {
            return base.Channel.ListadoUsuariosCalculoComison();
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoUsuariosCalculoComisonPorFechas(string fechIni, string fechFin) {
            return base.Channel.ListadoUsuariosCalculoComisonPorFechas(fechIni, fechFin);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoFacturasCalculoComison() {
            return base.Channel.ListadoFacturasCalculoComison();
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.ListadoUsuarios[] ListadoRecaudosCalculoComison() {
            return base.Channel.ListadoRecaudosCalculoComison();
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.DetalleUsuarios[] DetalleUsuariosCalculoComison(string codExtraccion) {
            return base.Channel.DetalleUsuariosCalculoComison(codExtraccion);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.LogExtraccionBH[] ExcelDetalleUsuario(string codExtraccion, string tipoLog, string idUsuario) {
            return base.Channel.ExcelDetalleUsuario(codExtraccion, tipoLog, idUsuario);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.DetalleFacturas[] DetalleFactura(string codExtraccion) {
            return base.Channel.DetalleFactura(codExtraccion);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.LogExtFacturacion[] ExcelDetalleFactura(string codExtraccion, string tipoLog) {
            return base.Channel.ExcelDetalleFactura(codExtraccion, tipoLog);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.DetalleFacturas[] DetalleRecaudo(string codExtraccion) {
            return base.Channel.DetalleRecaudo(codExtraccion);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Consultas.LogExtracionRecaudo[] ExcelDetalleRecaudo(string codExtraccion, string tipoLog) {
            return base.Channel.ExcelDetalleRecaudo(codExtraccion, tipoLog);
        }
    }
}
