//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColpatriaSAI.UI.MVC.wsAutenticacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.SeguridadDeUsuarios.LogicLay" +
        "er.RegistroDeUsuarios")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.Aplicacion[] AplicacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveAsesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.Estado EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoCivil EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaUltimoIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForzarCambioContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPUltimoIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NroHijosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiereValidacionEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.Genero SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.TipoIdentificacion TipoIdentificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Aplicacion[] Aplicaciones {
            get {
                return this.AplicacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.AplicacionesField, value) != true)) {
                    this.AplicacionesField = value;
                    this.RaisePropertyChanged("Aplicaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveAsesor {
            get {
                return this.ClaveAsesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveAsesorField, value) != true)) {
                    this.ClaveAsesorField = value;
                    this.RaisePropertyChanged("ClaveAsesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCiudad {
            get {
                return this.CodigoCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCiudadField, value) != true)) {
                    this.CodigoCiudadField = value;
                    this.RaisePropertyChanged("CodigoCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDepartamento {
            get {
                return this.CodigoDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDepartamentoField, value) != true)) {
                    this.CodigoDepartamentoField = value;
                    this.RaisePropertyChanged("CodigoDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCiudad {
            get {
                return this.DescripcionCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCiudadField, value) != true)) {
                    this.DescripcionCiudadField = value;
                    this.RaisePropertyChanged("DescripcionCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionDepartamento {
            get {
                return this.DescripcionDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionDepartamentoField, value) != true)) {
                    this.DescripcionDepartamentoField = value;
                    this.RaisePropertyChanged("DescripcionDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Estado Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoCivil EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((this.EstadoCivilField.Equals(value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaUltimoIngreso {
            get {
                return this.FechaUltimoIngresoField;
            }
            set {
                if ((this.FechaUltimoIngresoField.Equals(value) != true)) {
                    this.FechaUltimoIngresoField = value;
                    this.RaisePropertyChanged("FechaUltimoIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForzarCambioContrasena {
            get {
                return this.ForzarCambioContrasenaField;
            }
            set {
                if ((this.ForzarCambioContrasenaField.Equals(value) != true)) {
                    this.ForzarCambioContrasenaField = value;
                    this.RaisePropertyChanged("ForzarCambioContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPUltimoIngreso {
            get {
                return this.IPUltimoIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.IPUltimoIngresoField, value) != true)) {
                    this.IPUltimoIngresoField = value;
                    this.RaisePropertyChanged("IPUltimoIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NroHijos {
            get {
                return this.NroHijosField;
            }
            set {
                if ((this.NroHijosField.Equals(value) != true)) {
                    this.NroHijosField = value;
                    this.RaisePropertyChanged("NroHijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroIdentificacion {
            get {
                return this.NumeroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIdentificacionField, value) != true)) {
                    this.NumeroIdentificacionField = value;
                    this.RaisePropertyChanged("NumeroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequiereValidacionEmpresa {
            get {
                return this.RequiereValidacionEmpresaField;
            }
            set {
                if ((this.RequiereValidacionEmpresaField.Equals(value) != true)) {
                    this.RequiereValidacionEmpresaField = value;
                    this.RaisePropertyChanged("RequiereValidacionEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Genero Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.TipoIdentificacion TipoIdentificacion {
            get {
                return this.TipoIdentificacionField;
            }
            set {
                if ((this.TipoIdentificacionField.Equals(value) != true)) {
                    this.TipoIdentificacionField = value;
                    this.RaisePropertyChanged("TipoIdentificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aplicacion", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.SeguridadDeUsuarios.LogicLay" +
        "er.RegistroDeUsuarios")]
    [System.SerializableAttribute()]
    public partial class Aplicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.Perfil[] PerfilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Perfil[] Perfiles {
            get {
                return this.PerfilesField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilesField, value) != true)) {
                    this.PerfilesField = value;
                    this.RaisePropertyChanged("Perfiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publico {
            get {
                return this.PublicoField;
            }
            set {
                if ((this.PublicoField.Equals(value) != true)) {
                    this.PublicoField = value;
                    this.RaisePropertyChanged("Publico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.SeguridadDeUsuarios.LogicLay" +
        "er.Autenticacion")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_BLOQUEADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_INACTIVO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_PENDIENTEVALIDACION = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_NOENCONTRADO = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_PENDIENTECAMBIOCONTRASENA = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoCivil", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.BusinessEntities.Enumeration" +
        "s")]
    public enum EstadoCivil : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ST = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VD = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DV = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SP = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UL = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        O = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NA = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genero", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.BusinessEntities.Enumeration" +
        "s")]
    public enum Genero : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NA = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoIdentificacion", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.BusinessEntities.Enumeration" +
        "s")]
    public enum TipoIdentificacion : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CedulaDeCiudadania = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CedulaDeExtranjeria = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MenorSinIdentificar = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NumeroUnicoDeIdentificacionPersonal = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pasaporte = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegistroCivil = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TarjetaDeIdentidad = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Otro = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguno = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.SeguridadDeUsuarios.LogicLay" +
        "er.RegistroDeUsuarios")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.Empresa[] EmpresasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Empresa[] Empresas {
            get {
                return this.EmpresasField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresasField, value) != true)) {
                    this.EmpresasField = value;
                    this.RaisePropertyChanged("Empresas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publico {
            get {
                return this.PublicoField;
            }
            set {
                if ((this.PublicoField.Equals(value) != true)) {
                    this.PublicoField = value;
                    this.RaisePropertyChanged("Publico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.SeguridadDeUsuarios.LogicLay" +
        "er.RegistroDeUsuarios")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveAsesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DigitoVerificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroAfiliacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColpatriaSAI.UI.MVC.wsAutenticacion.TipoIdentificacion TipoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveAsesor {
            get {
                return this.ClaveAsesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveAsesorField, value) != true)) {
                    this.ClaveAsesorField = value;
                    this.RaisePropertyChanged("ClaveAsesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DigitoVerificacion {
            get {
                return this.DigitoVerificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DigitoVerificacionField, value) != true)) {
                    this.DigitoVerificacionField = value;
                    this.RaisePropertyChanged("DigitoVerificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAfiliacion {
            get {
                return this.NumeroAfiliacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroAfiliacionField, value) != true)) {
                    this.NumeroAfiliacionField = value;
                    this.RaisePropertyChanged("NumeroAfiliacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroIdentificacion {
            get {
                return this.NumeroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIdentificacionField, value) != true)) {
                    this.NumeroIdentificacionField = value;
                    this.RaisePropertyChanged("NumeroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEmpresa {
            get {
                return this.TipoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEmpresaField, value) != true)) {
                    this.TipoEmpresaField = value;
                    this.RaisePropertyChanged("TipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.TipoIdentificacion TipoIdentificacion {
            get {
                return this.TipoIdentificacionField;
            }
            set {
                if ((this.TipoIdentificacionField.Equals(value) != true)) {
                    this.TipoIdentificacionField = value;
                    this.RaisePropertyChanged("TipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valida {
            get {
                return this.ValidaField;
            }
            set {
                if ((this.ValidaField.Equals(value) != true)) {
                    this.ValidaField = value;
                    this.RaisePropertyChanged("Valida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoSegundaClave", Namespace="http://schemas.datacontract.org/2004/07/UI.Colpatria.SeguridadDeUsuarios.LogicLay" +
        "er.Autenticacion")]
    public enum EstadoSegundaClave : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_BLOQUEADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_SIN_CLAVE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FALLO_NOENCONTRADO = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsAutenticacion.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Autenticar", ReplyAction="http://tempuri.org/IService/AutenticarResponse")]
        ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario Autenticar(string idUsuario, string contrasena, string ip);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/Autenticar", ReplyAction="http://tempuri.org/IService/AutenticarResponse")]
        System.IAsyncResult BeginAutenticar(string idUsuario, string contrasena, string ip, System.AsyncCallback callback, object asyncState);
        
        ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario EndAutenticar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AutenticarSegundaClave", ReplyAction="http://tempuri.org/IService/AutenticarSegundaClaveResponse")]
        ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoSegundaClave AutenticarSegundaClave(string nombreUsuario, string segundaClave, string ip);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/AutenticarSegundaClave", ReplyAction="http://tempuri.org/IService/AutenticarSegundaClaveResponse")]
        System.IAsyncResult BeginAutenticarSegundaClave(string nombreUsuario, string segundaClave, string ip, System.AsyncCallback callback, object asyncState);
        
        ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoSegundaClave EndAutenticarSegundaClave(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AutenticaPorAplicacion", ReplyAction="http://tempuri.org/IService/AutenticaPorAplicacionResponse")]
        ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario AutenticaPorAplicacion(string idUsuario, string contrasena, string ip, string idAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/AutenticaPorAplicacion", ReplyAction="http://tempuri.org/IService/AutenticaPorAplicacionResponse")]
        System.IAsyncResult BeginAutenticaPorAplicacion(string idUsuario, string contrasena, string ip, string idAplicacion, System.AsyncCallback callback, object asyncState);
        
        ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario EndAutenticaPorAplicacion(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ColpatriaSAI.UI.MVC.wsAutenticacion.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AutenticarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticarSegundaClaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AutenticarSegundaClaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoSegundaClave Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoSegundaClave)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticaPorAplicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AutenticaPorAplicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ColpatriaSAI.UI.MVC.wsAutenticacion.IService>, ColpatriaSAI.UI.MVC.wsAutenticacion.IService {
        
        private BeginOperationDelegate onBeginAutenticarDelegate;
        
        private EndOperationDelegate onEndAutenticarDelegate;
        
        private System.Threading.SendOrPostCallback onAutenticarCompletedDelegate;
        
        private BeginOperationDelegate onBeginAutenticarSegundaClaveDelegate;
        
        private EndOperationDelegate onEndAutenticarSegundaClaveDelegate;
        
        private System.Threading.SendOrPostCallback onAutenticarSegundaClaveCompletedDelegate;
        
        private BeginOperationDelegate onBeginAutenticaPorAplicacionDelegate;
        
        private EndOperationDelegate onEndAutenticaPorAplicacionDelegate;
        
        private System.Threading.SendOrPostCallback onAutenticaPorAplicacionCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AutenticarCompletedEventArgs> AutenticarCompleted;
        
        public event System.EventHandler<AutenticarSegundaClaveCompletedEventArgs> AutenticarSegundaClaveCompleted;
        
        public event System.EventHandler<AutenticaPorAplicacionCompletedEventArgs> AutenticaPorAplicacionCompleted;
        
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario Autenticar(string idUsuario, string contrasena, string ip) {
            return base.Channel.Autenticar(idUsuario, contrasena, ip);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAutenticar(string idUsuario, string contrasena, string ip, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAutenticar(idUsuario, contrasena, ip, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario EndAutenticar(System.IAsyncResult result) {
            return base.Channel.EndAutenticar(result);
        }
        
        private System.IAsyncResult OnBeginAutenticar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idUsuario = ((string)(inValues[0]));
            string contrasena = ((string)(inValues[1]));
            string ip = ((string)(inValues[2]));
            return this.BeginAutenticar(idUsuario, contrasena, ip, callback, asyncState);
        }
        
        private object[] OnEndAutenticar(System.IAsyncResult result) {
            ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario retVal = this.EndAutenticar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAutenticarCompleted(object state) {
            if ((this.AutenticarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AutenticarCompleted(this, new AutenticarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AutenticarAsync(string idUsuario, string contrasena, string ip) {
            this.AutenticarAsync(idUsuario, contrasena, ip, null);
        }
        
        public void AutenticarAsync(string idUsuario, string contrasena, string ip, object userState) {
            if ((this.onBeginAutenticarDelegate == null)) {
                this.onBeginAutenticarDelegate = new BeginOperationDelegate(this.OnBeginAutenticar);
            }
            if ((this.onEndAutenticarDelegate == null)) {
                this.onEndAutenticarDelegate = new EndOperationDelegate(this.OnEndAutenticar);
            }
            if ((this.onAutenticarCompletedDelegate == null)) {
                this.onAutenticarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAutenticarCompleted);
            }
            base.InvokeAsync(this.onBeginAutenticarDelegate, new object[] {
                        idUsuario,
                        contrasena,
                        ip}, this.onEndAutenticarDelegate, this.onAutenticarCompletedDelegate, userState);
        }
        
        public ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoSegundaClave AutenticarSegundaClave(string nombreUsuario, string segundaClave, string ip) {
            return base.Channel.AutenticarSegundaClave(nombreUsuario, segundaClave, ip);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAutenticarSegundaClave(string nombreUsuario, string segundaClave, string ip, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAutenticarSegundaClave(nombreUsuario, segundaClave, ip, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoSegundaClave EndAutenticarSegundaClave(System.IAsyncResult result) {
            return base.Channel.EndAutenticarSegundaClave(result);
        }
        
        private System.IAsyncResult OnBeginAutenticarSegundaClave(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nombreUsuario = ((string)(inValues[0]));
            string segundaClave = ((string)(inValues[1]));
            string ip = ((string)(inValues[2]));
            return this.BeginAutenticarSegundaClave(nombreUsuario, segundaClave, ip, callback, asyncState);
        }
        
        private object[] OnEndAutenticarSegundaClave(System.IAsyncResult result) {
            ColpatriaSAI.UI.MVC.wsAutenticacion.EstadoSegundaClave retVal = this.EndAutenticarSegundaClave(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAutenticarSegundaClaveCompleted(object state) {
            if ((this.AutenticarSegundaClaveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AutenticarSegundaClaveCompleted(this, new AutenticarSegundaClaveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AutenticarSegundaClaveAsync(string nombreUsuario, string segundaClave, string ip) {
            this.AutenticarSegundaClaveAsync(nombreUsuario, segundaClave, ip, null);
        }
        
        public void AutenticarSegundaClaveAsync(string nombreUsuario, string segundaClave, string ip, object userState) {
            if ((this.onBeginAutenticarSegundaClaveDelegate == null)) {
                this.onBeginAutenticarSegundaClaveDelegate = new BeginOperationDelegate(this.OnBeginAutenticarSegundaClave);
            }
            if ((this.onEndAutenticarSegundaClaveDelegate == null)) {
                this.onEndAutenticarSegundaClaveDelegate = new EndOperationDelegate(this.OnEndAutenticarSegundaClave);
            }
            if ((this.onAutenticarSegundaClaveCompletedDelegate == null)) {
                this.onAutenticarSegundaClaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAutenticarSegundaClaveCompleted);
            }
            base.InvokeAsync(this.onBeginAutenticarSegundaClaveDelegate, new object[] {
                        nombreUsuario,
                        segundaClave,
                        ip}, this.onEndAutenticarSegundaClaveDelegate, this.onAutenticarSegundaClaveCompletedDelegate, userState);
        }
        
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario AutenticaPorAplicacion(string idUsuario, string contrasena, string ip, string idAplicacion) {
            return base.Channel.AutenticaPorAplicacion(idUsuario, contrasena, ip, idAplicacion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAutenticaPorAplicacion(string idUsuario, string contrasena, string ip, string idAplicacion, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAutenticaPorAplicacion(idUsuario, contrasena, ip, idAplicacion, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario EndAutenticaPorAplicacion(System.IAsyncResult result) {
            return base.Channel.EndAutenticaPorAplicacion(result);
        }
        
        private System.IAsyncResult OnBeginAutenticaPorAplicacion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idUsuario = ((string)(inValues[0]));
            string contrasena = ((string)(inValues[1]));
            string ip = ((string)(inValues[2]));
            string idAplicacion = ((string)(inValues[3]));
            return this.BeginAutenticaPorAplicacion(idUsuario, contrasena, ip, idAplicacion, callback, asyncState);
        }
        
        private object[] OnEndAutenticaPorAplicacion(System.IAsyncResult result) {
            ColpatriaSAI.UI.MVC.wsAutenticacion.Usuario retVal = this.EndAutenticaPorAplicacion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAutenticaPorAplicacionCompleted(object state) {
            if ((this.AutenticaPorAplicacionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AutenticaPorAplicacionCompleted(this, new AutenticaPorAplicacionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AutenticaPorAplicacionAsync(string idUsuario, string contrasena, string ip, string idAplicacion) {
            this.AutenticaPorAplicacionAsync(idUsuario, contrasena, ip, idAplicacion, null);
        }
        
        public void AutenticaPorAplicacionAsync(string idUsuario, string contrasena, string ip, string idAplicacion, object userState) {
            if ((this.onBeginAutenticaPorAplicacionDelegate == null)) {
                this.onBeginAutenticaPorAplicacionDelegate = new BeginOperationDelegate(this.OnBeginAutenticaPorAplicacion);
            }
            if ((this.onEndAutenticaPorAplicacionDelegate == null)) {
                this.onEndAutenticaPorAplicacionDelegate = new EndOperationDelegate(this.OnEndAutenticaPorAplicacion);
            }
            if ((this.onAutenticaPorAplicacionCompletedDelegate == null)) {
                this.onAutenticaPorAplicacionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAutenticaPorAplicacionCompleted);
            }
            base.InvokeAsync(this.onBeginAutenticaPorAplicacionDelegate, new object[] {
                        idUsuario,
                        contrasena,
                        ip,
                        idAplicacion}, this.onEndAutenticaPorAplicacionDelegate, this.onAutenticaPorAplicacionCompletedDelegate, userState);
        }
    }
}
