//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColpatriaSAI.UI.MVC.Reportes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Reportes.IReportes")]
    public interface IReportes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/GetReporteBeneficiarios", ReplyAction="http://tempuri.org/IReportes/GetReporteBeneficiariosResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteBeneficiarioClass[] GetReporteBeneficiarios(int año, int mes, string ClavesAsesor, string IdDirector, string IdGerente, int CanalVentasId, int SubCanalId, int TipoPlan, int TipoContrato, int modelo, int sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/GetReporteDetalleBeneficiarios", ReplyAction="http://tempuri.org/IReportes/GetReporteDetalleBeneficiariosResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteDetalleBeneficiariosClass[] GetReporteDetalleBeneficiarios(int anio, int mes, string ClavesAsesor, string IdDirector, string IdGerente, int CanalVentasId, int SubCanalId, int TipoPlan, int TipoContrato, int modelo, int sucursal, string numerocontrato, int estadoBeneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/GetReporteTransferencias", ReplyAction="http://tempuri.org/IReportes/GetReporteTransferenciasResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteTrasnferenciasClass[] GetReporteTransferencias(System.DateTime pFechaPeriodo, int pAsesorInicial, int pAsesorFinal, int pCanalVentas, int pSubCanal, int pDirector, int pGerOfic, int pGerReg, string pNumeroContrato, string pSubContrato, int pTipoPlan, int pTipoContrato, int pTipoTransferencia, int modelo, int sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/GetReporteAsesores", ReplyAction="http://tempuri.org/IReportes/GetReporteAsesoresResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteAsesoresClass[] GetReporteAsesores(int año, int mes, string pClavesAsesor, int pCanalVenta, int pSubCanal, int IdGerente, int IdDirector, int modelo, int sucursal);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportes/GetReportBHDeferred", ReplyAction = "http://tempuri.org/IReportes/GetReportBHDeferredResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReportBHDeferredClass[] GetReportBHDeferred(System.DateTime DateIni , System.DateTime DateFin , int Format, int ProcessType , string UserName );

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportes/GetReportBHAccrued", ReplyAction = "http://tempuri.org/IReportes/GetReportBHAccruedResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReportBHAccruedClass[] GetReportBHAccrued(System.DateTime DateIni, System.DateTime DateFin, int Format, int ProcessType, string UserName);


        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/GetReporteLiderComercial", ReplyAction="http://tempuri.org/IReportes/GetReporteLiderComercialResponse")]
        ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteAsesoresClass[] GetReporteLiderComercial(int año, int mes, string pClavesAsesor, int pCanalVenta, int pSubCanal, int IdGerente, int IdDirector, int modelo, int sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ValidaDirector", ReplyAction="http://tempuri.org/IReportes/ValidaDirectorResponse")]
        int ValidaDirector(string IdDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/GetInfoPagoAsesorPortal", ReplyAction="http://tempuri.org/IReportes/GetInfoPagoAsesorPortalResponse")]
        System.Collections.Generic.Dictionary<string, string> GetInfoPagoAsesorPortal(int idLiquidacion, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/GetLiquidacionesPortalAsesor", ReplyAction="http://tempuri.org/IReportes/GetLiquidacionesPortalAsesorResponse")]
        System.Collections.Generic.Dictionary<int, string> GetLiquidacionesPortalAsesor();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportes/GetAvaliablePeriodsBH", ReplyAction = "http://tempuri.org/IReportes/GetAvaliablePeriodsBH")]
        System.Collections.Generic.Dictionary<int, string> GetAvaliablePeriodsBH(); 
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportesChannel : ColpatriaSAI.UI.MVC.Reportes.IReportes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportesClient : System.ServiceModel.ClientBase<ColpatriaSAI.UI.MVC.Reportes.IReportes>, ColpatriaSAI.UI.MVC.Reportes.IReportes {
        
        public ReportesClient() {
        }
        
        public ReportesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteBeneficiarioClass[] GetReporteBeneficiarios(int año, int mes, string ClavesAsesor, string IdDirector, string IdGerente, int CanalVentasId, int SubCanalId, int TipoPlan, int TipoContrato, int modelo, int sucursal) {
            return base.Channel.GetReporteBeneficiarios(año, mes, ClavesAsesor, IdDirector, IdGerente, CanalVentasId, SubCanalId, TipoPlan, TipoContrato, modelo, sucursal);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteDetalleBeneficiariosClass[] GetReporteDetalleBeneficiarios(int anio, int mes, string ClavesAsesor, string IdDirector, string IdGerente, int CanalVentasId, int SubCanalId, int TipoPlan, int TipoContrato, int modelo, int sucursal, string numerocontrato, int estadoBeneficiario) {
            return base.Channel.GetReporteDetalleBeneficiarios(anio, mes, ClavesAsesor, IdDirector, IdGerente, CanalVentasId, SubCanalId, TipoPlan, TipoContrato, modelo, sucursal, numerocontrato, estadoBeneficiario);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteTrasnferenciasClass[] GetReporteTransferencias(System.DateTime pFechaPeriodo, int pAsesorInicial, int pAsesorFinal, int pCanalVentas, int pSubCanal, int pDirector, int pGerOfic, int pGerReg, string pNumeroContrato, string pSubContrato, int pTipoPlan, int pTipoContrato, int pTipoTransferencia, int modelo, int sucursal) {
            return base.Channel.GetReporteTransferencias(pFechaPeriodo, pAsesorInicial, pAsesorFinal, pCanalVentas, pSubCanal, pDirector, pGerOfic, pGerReg, pNumeroContrato, pSubContrato, pTipoPlan, pTipoContrato, pTipoTransferencia, modelo, sucursal);
        }
        
        public ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteAsesoresClass[] GetReporteAsesores(int año, int mes, string pClavesAsesor, int pCanalVenta, int pSubCanal, int IdGerente, int IdDirector, int modelo, int sucursal) {
            return base.Channel.GetReporteAsesores(año, mes, pClavesAsesor, pCanalVenta, pSubCanal, IdGerente, IdDirector, modelo, sucursal);
        }

        public ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReportBHDeferredClass[] GetReportBHDeferred(System.DateTime DateIni, System.DateTime DateFin, int Format, int ProcessType, string UserName)
        {
            return base.Channel.GetReportBHDeferred(DateIni,DateFin,Format,ProcessType,UserName);
        }

        public ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReportBHAccruedClass[] GetReportBHAccrued(System.DateTime DateIni, System.DateTime DateFin, int Format, int ProcessType, string UserName)
        {
            return base.Channel.GetReportBHAccrued(DateIni, DateFin, Format, ProcessType, UserName);
        }

        public ColpatriaSAI.Negocio.Componentes.Comision.Reportes.ReporteAsesoresClass[] GetReporteLiderComercial(int año, int mes, string pClavesAsesor, int pCanalVenta, int pSubCanal, int IdGerente, int IdDirector, int modelo, int sucursal) {
            return base.Channel.GetReporteLiderComercial(año, mes, pClavesAsesor, pCanalVenta, pSubCanal, IdGerente, IdDirector, modelo, sucursal);
        }
        
        public int ValidaDirector(string IdDocumento) {
            return base.Channel.ValidaDirector(IdDocumento);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetInfoPagoAsesorPortal(int idLiquidacion, string clave) {
            return base.Channel.GetInfoPagoAsesorPortal(idLiquidacion, clave);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetLiquidacionesPortalAsesor() {
            return base.Channel.GetLiquidacionesPortalAsesor();
        }

        public System.Collections.Generic.Dictionary<int, string> GetAvaliablePeriodsBH()
        {
            return base.Channel.GetAvaliablePeriodsBH();
        }
    }
}
